import { redirect, notFound } from 'next/navigation';
import { getSession } from '@/lib/auth';
import { createClient } from '@/lib/supabase/server';
import { EditDetailPageClient } from './page-client';
import { getDocument, getDocumentFiles } from '@/lib/server/services/documentService';

export default async function EditDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { session, user } = await getSession();

  if (!session) {
    redirect('/login');
  }

  const { id } = await params;
  const supabase = await createClient();

  // Get document
  const document = await getDocument(supabase, id);

  if (!document) {
    notFound();
  }

  // Verify user has access and get source settings
  const { data: repo } = await supabase
    .from('workspace_sources')
    .select('user_id, settings, repo_url, external_url, default_branch')
    .eq('id', document.source_id)
    .single();

  if (!repo || repo.user_id !== user.id) {
    notFound();
  }

  // Get source setup to get the branch used for setup
  const { data: setup } = await supabase
    .from('source_setup')
    .select('branch')
    .eq('source_id', document.source_id)
    .single();

  // Get file paths
  const filePaths = await getDocumentFiles(supabase, id);

  // Check for pending review generated by automation
  const { data: pendingReview } = await supabase
    .from('document_versions')
    .select('id, created_at')
    .eq('document_id', id)
    .eq('status', 'pending')
    .order('created_at', { ascending: false })
    .limit(1)
    .maybeSingle();

  // Extract prompt config from repo settings
  const repoSettings = (repo.settings || {}) as {
    llm_prompt_config?: Record<string, unknown>;
    model?: string;
    document_structure?: Record<string, unknown>;
  };

  // Get configuration from document if available, otherwise fall back to repo settings
  const documentConfig = document.configuration || {};
  const regenerationSettings = documentConfig;

  // Format as submission for backward compatibility with client component
  const submission = {
    id: String(document.id),
    created_date: document.created_at as string,
    title: document.title ?? 'Untitled',
    markdown: document.content ?? '',
    status: 'completed' as const,
    error_message: null as string | null,
    input_type: 'github_repo' as const,
    input_content: '',
    summary: document.content.replace(/\s+/g, ' ').slice(0, 200),
    pending_review: pendingReview
      ? {
          id: pendingReview.id,
          created_at: pendingReview.created_at,
        }
      : null,
    source_meta: {
      repoId: document.source_id,
      repoUrl: repo.repo_url || repo.external_url,
      branch: setup?.branch || repo.default_branch || 'main',
      llm_prompt_config: regenerationSettings || repoSettings.llm_prompt_config || null,
      model: regenerationSettings.model || repoSettings.model || null,
      document_structure: regenerationSettings.documentStructure || repoSettings.document_structure || null,
    },
    code_snapshot: undefined,
    is_outdated: false,
    selected_files: filePaths
  };

  return <EditDetailPageClient submission={submission} />;
}
