/**
 * API Endpoint: OAuth Callback Handler
 * 
 * Handles the OAuth callback from Nango after user authorization
 * Stores the connection token securely in Supabase
 */

import type { RequestHandler } from '@sveltejs/kit';
import { json, redirect } from '@sveltejs/kit';
import { NANGO_CONFIG } from '$lib/server/nango/config';

function jsonResponse(data: unknown, status = 200) {
	return json(data, { status });
}

export const GET: RequestHandler = async ({ url, locals }) => {
	try {
		// Get query parameters from Nango callback
		const connectionId = url.searchParams.get('connection_id');
		const providerConfigKey = url.searchParams.get('provider_config_key');
		const error = url.searchParams.get('error');

		if (error) {
			console.error('OAuth error:', error);
			return redirect(302, '/integrations?error=' + encodeURIComponent(error));
		}

		if (!connectionId || !providerConfigKey) {
			return jsonResponse({ error: 'Missing connection_id or provider_config_key' }, 400);
		}

		// Verify the user is authenticated
		const { user } = await locals.safeGetSession();
		if (!user) {
			return jsonResponse({ error: 'Unauthorized' }, 401);
		}

		// Note: With Connect sessions, connection IDs are UUIDs generated by Nango
		// We can't extract user ID from them. Instead, we verify the connection
		// belongs to the current user by checking Nango's connection data

		// Fetch the connection details from Nango
		const nangoUrl = new URL(`/connection/${connectionId}`, NANGO_CONFIG.host);
		nangoUrl.searchParams.set('provider_config_key', providerConfigKey);
		
		const response = await fetch(nangoUrl.toString(), {
			headers: {
				'Authorization': `Bearer ${NANGO_CONFIG.secretKey}`,
				'Content-Type': 'application/json'
			}
		});

		if (!response.ok) {
			const errorText = await response.text();
			throw new Error(`Nango API error: ${response.status} ${errorText}`);
		}

		const connectionData = await response.json();

		// Verify the connection belongs to this user by checking end_user.id
		// (This matches the end_user.id we passed when creating the Connect session)
		if (connectionData.end_user?.id && connectionData.end_user.id !== user.id) {
			return jsonResponse({ error: 'Connection does not belong to this user' }, 403);
		}

		// Store the connection in Supabase
		const { error: dbError } = await locals.supabase
			.from('oauth_connections')
			.upsert({
				user_id: user.id,
				provider: providerConfigKey,
				connection_id: connectionId,
				status: 'active',
				// Store metadata (not the actual token - Nango handles that)
				metadata: {
					provider_config_key: providerConfigKey,
					connected_at: new Date().toISOString(),
					// You can store additional metadata here
				},
				updated_at: new Date().toISOString()
			}, {
				onConflict: 'user_id,provider'
			});

		if (dbError) {
			console.error('Failed to store connection:', dbError);
			return jsonResponse({ error: 'Failed to store connection' }, 500);
		}

		// Redirect to integrations page with success message
		return redirect(302, '/integrations?success=true&provider=' + encodeURIComponent(providerConfigKey));
	} catch (err: any) {
		console.error('OAuth callback error:', err);
		return redirect(302, '/integrations?error=' + encodeURIComponent(err.message || 'Unknown error'));
	}
};

